### ISSUE TITLE
1st storly dont show 

### ISSUE THREAD

**Issue by charischung** [Netvent/storyly-mobile#127] opened 2021-08-09 10:16 UTC
![image](https://user-images.githubusercontent.com/58552069/128691633-779dd7df-e945-46f3-939f-53161318add5.png)

## Environment Details
**Storyly SDK Version:** 1.13.0
**Android SDK Version:** 1.13.0

1st storly dont show

**Comment by levent-oral** [comment] 2021-08-09 10:59
Hello @charischung,

We couldn't reproduce the case with Storyly demo applications but we've observed with your application. 

We've checked another instance, inside your 'Feed' tab and Storyly is showing correctly and fully, can you confirm this as well? 
Is there any custom animation to show Storyly in your 'Home' tab during scroll action?

We've also checked that when you scroll to end and comeback to start position, it's showing correctly again. Can you confirm this as well?

If you can create a PR or share a demo project that contains constant reproduce case for this issue, it'll help us to understand the case correctly.

Thanks,

**Comment by charischung** [comment] 2021-08-10 09:38
@levent-oral 
![image](https://user-images.githubusercontent.com/58552069/128844743-640c733e-5057-45b9-beb0-cc8fe0f00c17.png)

**Comment by levent-oral** [comment] 2021-09-25 09:10
Hi @charischung ,

We've made a fix for this issue in [1.5.2](https://github.com/Netvent/storyly-mobile/blob/master/android/RELEASENOTES.md#1152-24092021). We've reproduced the issue when StorylyView is recreated/reinitialized inside RecyclerView usage. So, please update and test accordingly if this is your case.

In addition to that, we've prepared a sample usage and some minor reminders about StorylyView inside RecyclerView usage, check it on [RecyclerView Sample](https://github.com/Netvent/storyly-mobile/blob/master/android/kotlin/StorylyDemo/app/src/main/java/com/appsamurai/storylydemo/RecyclerViewActivity.kt)

Thanks,

**Closed** 2021-11-05 07:41 UTC
Labels: bug, android
