### ISSUE TITLE
android issue in SDK 1.9.5

### ISSUE THREAD

**Issue by charischung415** [Netvent/storyly-mobile#83] opened 2021-04-09 03:45 UTC
[李澄锋_2021-04-09 09 40 45.txt](https://github.com/Netvent/storyly-mobile/files/6283023/_2021-04-09.09.40.45.txt)

**Comment by levent-oral** [comment] 2021-04-09 10:01
Duplicate of #74.

**Closed by levent-oral** 2021-04-09 10:01 UTC
Labels: android, bug
